### ISSUE TITLE
NEED HELP

### ISSUE THREAD

**Issue by MASSI22** [KayesFahim/Python-Automation#1]
OTP By Pass

**Comment by parmonov98** [comment]
> OTP By Pass

How can we bypass proxy security on vfsglobal?

**Comment by KayesFahim** [comment]
Proxy security can by pass by using selenium chrome

**Comment by parmonov98** [comment]
> Proxy security can by pass by using selenium chrome

how eactly?

**Comment by KayesFahim** [comment]
can you please share code

**Comment by sohan724flyfar** [comment]
sure. your work on top-notch i appreciate your work..❤❤👏
